### ISSUE TITLE
Navicat Premium 16 release

### ISSUE THREAD

**Issue by killdayu** [wctsai20002/navicat-refresh#3]
Does it too apply?

**Comment by wctsai20002** [comment]
Seems this bat can also apply to navicat premium 16 in my environment.
I will check more comprehensively later.
If this bat not work well, please tell me the version and language you use.

**Comment by killdayu** [comment]
> Seems this bat can also apply to navicat premium 16 in my environment. I will check more comprehensively later. If this bat not work well, please tell me the version and language you use.

it can work,very think you!
