### ISSUE TITLE
Navicat 16.3.2 not working

### ISSUE THREAD

**Issue by Danydeidei** [wctsai20002/navicat-refresh#8]
I used your code on previous Navicat Premium versione and it works.
With the last Navicat Premium (16.3.2) and Navicat for Postgres (16.3.2) is not working
WIN 11

**Comment by abela-a** [comment]
for now, just downgrade your navicat.

**Comment by taozuhong** [comment]
欢迎各位体验[**袋鼠数据库工具**](https://www.datatable.online/en/)


[![Workspace](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/a57b7fe8-aea8-4f1c-926e-374e6b03c27b)](https://www.datatable.online/en/)
[![Kangaroo-newlook2](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/1e932afe-e78a-4086-ac73-dfaf6eadb921)](https://www.datatable.online/en/)
